---
version: "3"
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html:delegated
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: em2008
    ports:
      - "3307:3306"
